// Mocks generated by Mockito 5.4.5 from annotations
// in enpal_tech_chall/test/data/monitoring/remote/impl/monitoring.remote.data_source.impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:enpal_tech_chall/core/enums/energy_type.enum.dart' as _i5;
import 'package:enpal_tech_chall/data/networking/endpoints/monitoring.endpoint.dart'
    as _i2;
import 'package:enpal_tech_chall/data/networking/responses/monitoring.model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MonitoringEndpoint].
///
/// See the documentation for Mockito's code generation for more information.
class MockMonitoringEndpoint extends _i1.Mock
    implements _i2.MonitoringEndpoint {
  @override
  _i3.Future<List<_i4.MonitoringRemoteModel>> getMonitoring({
    required String? date,
    required _i5.EnergyType? energyType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMonitoring, [], {
              #date: date,
              #energyType: energyType,
            }),
            returnValue: _i3.Future<List<_i4.MonitoringRemoteModel>>.value(
              <_i4.MonitoringRemoteModel>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.MonitoringRemoteModel>>.value(
                  <_i4.MonitoringRemoteModel>[],
                ),
          )
          as _i3.Future<List<_i4.MonitoringRemoteModel>>);
}
